name: Handle prod* Tag

on:
  push:
    tags:
      - 'prod*'

jobs:
  manage-prod-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "Zayam-Amjad"
          git config --global user.email "zayam.amjad@dubizzlelabs.com"

      - name: Delete existing prod* tag from remote (if exists)
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "Detected tag: $TAG_NAME"
          if git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME"; then
            echo "Deleting remote tag: $TAG_NAME"
            git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Zayam-Amjad/Try.git :refs/tags/$TAG_NAME
          else
            echo "No existing tag to delete."
          fi

      - name: Re-push prod* tag to remote
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          git tag -f "$TAG_NAME"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Zayam-Amjad/Try.git "$TAG_NAME" --force
