name: Handle prod Tag from Manual Input

on:
  workflow_dispatch:
    inputs:
      release_input:
        description: 'Release string in the format: release-olx-app 1.2.3'
        required: true
        type: string

jobs:
  manage-prod-tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to delete and push tags

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name from input
        id: extract_tag
        run: |
          echo "Input: ${{ github.event.inputs.release_input }}"
          TAG_NAME=$(echo "${{ github.event.inputs.release_input }}" | awk '{print $2}')
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Delete tag from remote if exists
        run: |
          TAG_NAME="${{ steps.extract_tag.outputs.tag }}"
          echo "Detected tag: $TAG_NAME"
          if git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME"; then
            echo "Deleting remote tag: $TAG_NAME"
            git push origin :refs/tags/$TAG_NAME
          else
            echo "No existing remote tag to delete."
          fi

      - name: Re-push tag to remote
        run: |
          TAG_NAME="${{ steps.extract_tag.outputs.tag }}"
          echo "Re-pushing tag: $TAG_NAME"
          git tag -f "$TAG_NAME"
          git push origin "$TAG_NAME" --force
